
spring.application.name=PFA_Back


server.port=8080
server.address=0.0.0.0


spring.elasticsearch.uris=http://localhost:9200/

# Emplacements des ressources statiques et des fichiers uploadés
spring.web.resources.static-locations=classpath:/static/,file:uploads/

# Répertoires pour les uploads de fichiers spécifiques
file.upload-dir.audio=uploads/audio
file.upload-dir.images=uploads/images

# URL de base pour l'accès aux fichiers (si nécessaire)
file.base-url=http://localhost:8080

# URL du service de recommandation externe
recommendation.service.url=http://localhost:8000


spring.kafka.bootstrap-servers=localhost:9092


spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer


spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer


kafka.topic.user-interaction=user-interactions-topic


spring.kafka.properties.spring.json.add.type.headers=false


app.image-base-url=http://localhost:8080/api



kafka.topic.recommendation=recommandation


spring.kafka.consumer.properties.spring.json.trusted.packages=org.dami.pfa_back.DTO,java.util.List
